### ISSUE TITLE
Allikas: Album Academicum

### ISSUE THREAD

**Issue by mitselek** [memoriaal/memoriaal#7]
### Album Academicum Universitatis Tartuensis 1918-1944
 
- [Näidislink allikale](https://www.ra.ee/apps/andmed/index.php/matrikkel/view?id=11206)
- Lähtefail [album_academicum.csv](https://github.com/memoriaal/memoriaal/files/13176071/album_academicum.csv)
- Vahetabel [Album Academicum](https://docs.google.com/spreadsheets/d/1cF_XTqCFOSQUGvr4lvuF8pk9ozDrZ9UMy_hpW0RKjYk/edit#gid=1939905177)

**Teha**
- [x] Kirjekoodid AA-1234567
- [x] tulp **RA link** linkida **RA id** -> www\.ra.ee/apps/andmed/index.php/matrikkel/view?id=**:RA id**
- [x] tulp **Matrikkel** linkida **fond 2100, nimistu 1** -> ais.ra.ee/et/description-unit/search?refcode=EAA.2100.1.**:fond 2100, nimistu 1**&size=20
- [x] surmaajad tõlkida
- [X] importida nimed-aastad-elulugu-viited - repis.import.album_academicum
- [x] Nimede tulbad harutada "nimi" ja "teised nimed"
      Selle asemel teha nimekujudest ja kuupäevadest indeks
- [x] impordiskriptid persoonikoodi kaudu sidumiseks
- [x] uued funktsioonid `repis.func_person_born(in_persoon)` ja `repis.func_person_dead(in_persoon)` targema sünni- ja surmaaja arvutamiseks persooni juurde

**Comment by mitselek** [comment]
import'i baasis on kolm tabelit:

- aa_eesnimed
  - kirjekood
  - eesnimi
- aa_perenimed
  - kirjekood
  - perenimi
- aa_synd
  - kirjekood
  - sünd (AAAA-KK-PP)
  - sünd7 (AAAA-KK)
  - sünd4 (AAAA)

nende abil saab teha kiireid päringuid muude tabelite vastu; nt persoonide tabelist:
``` sql
SELECT aa.kirjekood, aa.eesnimi_orig, aa.perenimi_orig, aa.sünd, k0.*
FROM import.album_academicum aa
LEFT JOIN import.aa_eesnimed aae ON aae.kirjekood = aa.kirjekood
LEFT JOIN import.aa_perenimed aap ON aap.kirjekood = aa.kirjekood
LEFT JOIN import.aa_synd aas ON aas.kirjekood = aa.kirjekood
LEFT JOIN repis.kirjed k0 ON k0.eesnimi = aae.eesnimi 
                         AND k0.Perenimi = aap.perenimi
                         AND k0.Sünd = aas.sünd
WHERE aa.persoon IS NULL
AND k0.persoon IS NOT NULL;
```

**Comment by UlleKr** [comment]
Sünniajad AA-st kirjereale - praegu need ei uuene, kui puudu.

**Comment by mitselek** [comment]
persoonid, kellel on AA kirjes täpsem sünniaeg, kui persooni juures:
```sql
SELECT kp.kirjekood, ka.sünd, kp.*
FROM repis.kirjed kp
LEFT JOIN repis.kirjed ka ON kp.kirjekood = ka.persoon AND ka.allikas = 'aa' and LENGTH(ka.sünd) > LENGTH(kp.sünd)
WHERE kp.allikas = 'persoon'
  AND ka.persoon IS NOT NULL
  AND kp.`Sünd` > ''
;
```

sama käib ka surmaaegade kohta - kirjed, kus persooni surmaaeg on väiksema täpsusega, kui AA:
```sql
SELECT * FROM repis.kirjed 
WHERE persoon IN (
SELECT kp.kirjekood
FROM repis.kirjed kp
LEFT JOIN repis.kirjed ka ON kp.kirjekood = ka.persoon AND ka.allikas = 'aa' and LENGTH(ka.surm) > LENGTH(kp.surm)
WHERE kp.allikas = 'persoon'
  AND ka.persoon IS NOT NULL
  AND kp.surm > '' )
ORDER BY persoon, kirjekood
;

```

**Comment by mitselek** [comment]
Lahenduseks persoonikirje arvutamise loogika parandus, kus sünni- ja surmadaatumite arvutus käiks sedasi:
1. prioriseeri kuupäevad
2. vali prioriteetseim -> _kuupäev_
3. kui pikkus on väiksem, kui 10, siis
4. otsi nimekirjast järgmine, mille algus on sama aga pikkus suurem -> _kuupäev_
5. kui nimekiri pole läbitud, siis tagasi iii.

Uued funktsioonid `repis.func_person_born(in_persoon)` ja `repis.func_person_dead(in_persoon)` tagastavad "parima" kuupäeva.
